version: '3.0'

services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./homeassistant/:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_HA_DATABASE}
      - MYSQL_USER=${MYSQL_HA_USER}
      - MYSQL_PASSWORD=${MYSQL_HA_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./mariadb:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: unless-stopped
    environment:
      - PMA_HOST=mariadb
      #- PMA_USER=root
      #- PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    ports:
      - 8090:80
    depends_on:
      - mariadb

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883/tcp
    
#  zigbee2mqtt:
#    container_name: zigbee2mqtt
#    image: koenkk/zigbee2mqtt:latest
#    restart: unless-stopped
#    devices:
#      - ${ZIGBEE_ADAPTER_TTY}:/dev/ttyACM0
#    environment:
#      - TZ=Europe/Moscow
#    volumes:
#      - ./zigbee2mqtt:/app/data
#      - /run/udev:/run/udev:ro
#    ports:
#      - 8020:8020
#    depends_on:
#      - mosquitto

  esphome:
    container_name: esphome
    image: esphome/esphome:latest
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - TZ=Europe/Moscow
      - ESPHOME_DASHBOARD_USE_PING=true
    volumes:
      - ./esphome/config:/config
      - /etc/localtime:/etc/localtime:ro

  nodered:
    container_name: nodered
    image: nodered/node-red:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./nodered:/data
    ports:
      - 1880:1880/tcp
    depends_on:
      - homeassistant
      - mosquitto
  
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
    volumes:
      - ./:/config/workspace
    ports:
      - 8443:8443